# __init__.py

bl_info = {
    "name": "Mouth Shape Animator",
    "blender": (3, 3, 0),  # Ensure compatibility with your Blender version but also with RLPS
    "category": "Animation",  # Category under which it will be listed in Blender
    "author": "OrganicMonkeyMotion",  # Your name
    "version": (0, 1, 0),  # Version number
    "description": "Import and animate mouth shapes from JSON as generated by RLPS.",  # Short description
    "support": "COMMUNITY",
    "tracker_url": "https://github.com/OrganicMonkeyMotion/mouth_shape_animator/issues",
}

import bpy
from . import mouth_shape_animator  # Import the main functionality from another file

def register():
    mouth_shape_animator.register()  # Call the register function from your main code
    print("Mouth Shape Animator for RLPS registered successfully!")

def unregister():
    mouth_shape_animator.unregister()  # Call the unregister function from your main code
    print("Mouth Shape Animator for RLPS unregistered successfully!")

if __name__ == "__main__":
    register()
